name: Pull Request Summary
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  pull-request-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Pull request summary
        uses: ai-action/pull-request-summary@v2
